// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ExpandLineSelection
{
    internal sealed partial class Vsix
    {
        public const string Id = "ExpandLineSelection.cd67f2d4-d918-491d-aa60-4e5d102fc3ab";
        public const string Name = "Expand Line Selection";
        public const string Description = @"A reproduction of the Expand Line Selection command implemented in VSCode.";
        public const string Language = "en-US";
        public const string Version = "1.0.1";
        public const string Author = "Kazuma Ito";
        public const string Tags = "select";
    }
}
